
EXEC_PATH=./build/
SRC_PATH=../src/
LTYPES_PATH=./ltypes/
EXT=.exe

all: ltypes_test ltypes_test_1

ltypes_test: 
	gcc -o $(EXEC_PATH)/ltypes_test_1$(EXT) $(LTYPES_PATH)/ltypes_test_1.c $(SRC_PATH)/lstring.c
    
ltypes_test_1:
	$(EXEC_PATH)/ltypes_test_1$(EXT)